
stages:
  - build
  - scan

# build job
build_app:
  stage: build
  image: maven:3.6.3-openjdk-8

  # actually do the work - as a script (series of commands to execute)
  #   need to install the basic tools on the Docker image (maven & java)
  script:
    - mvn clean package

  # save the output from this job  
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour

# scan job
veracode_scan:
  stage: scan
  image: veracode/api-wrapper-java:latest

  script:
    - VFILE=`ls target`
    - echo $VFILE
    - TIMESTAMP=`date "+%Y-%m-%d_%H:%M"`
    - echo $TIMESTAMP
    - echo $CI_JOB_ID
    - java -jar /opt/veracode/api-wrapper.jar
      -vid $VERACODE_API_ID
      -vkey $VERACODE_API_KEY
      -action uploadandscan
      -appname "SonarQube plugin"
      -createprofile "false"
      -version "GitLab-CI-$TIMESTAMP-($CI_JOB_ID)"
      -filepath target/$VFILE
