
stages:
  - build
  - scan

# build job
maven_build:
  # jobs execute within a stage
  stage: build

  # we require a runner that has docker
  tags:
    - docker

  # actually do the work - as a script
  script:
    - echo "Building"
    - uname -a
    - apt-get update
    - apt-get --assume-yes install openjdk-8-jdk
    - apt-get --assume-yes install maven
    - mvn --version
    - mvn package



# scan

